[2023-08-12T03:57:56.728+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_dag.tune_task manual__2023-08-12T03:57:25.413988+00:00 [queued]>
[2023-08-12T03:57:56.732+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_dag.tune_task manual__2023-08-12T03:57:25.413988+00:00 [queued]>
[2023-08-12T03:57:56.732+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-08-12T03:57:56.736+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): tune_task> on 2023-08-12 03:57:25.413988+00:00
[2023-08-12T03:57:56.741+0000] {standard_task_runner.py:57} INFO - Started process 223 to run task
[2023-08-12T03:57:56.742+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'tune_dag', 'tune_task', 'manual__2023-08-12T03:57:25.413988+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/scripts/tune_ml.py', '--cfg-path', '/tmp/tmpakudnf_9']
[2023-08-12T03:57:56.743+0000] {standard_task_runner.py:85} INFO - Job 64: Subtask tune_task
[2023-08-12T03:57:56.760+0000] {task_command.py:410} INFO - Running <TaskInstance: tune_dag.tune_task manual__2023-08-12T03:57:25.413988+00:00 [running]> on host 667da7879368
[2023-08-12T03:57:56.790+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thanhdong18891@gmail.com' AIRFLOW_CTX_DAG_OWNER='DongNT17' AIRFLOW_CTX_DAG_ID='tune_dag' AIRFLOW_CTX_TASK_ID='tune_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-12T03:57:25.413988+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-12T03:57:25.413988+00:00'
[2023-08-12T03:57:56.791+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-12T03:57:56.791+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', ' bash -i /opt/***/dags/scripts/train.sh ']
[2023-08-12T03:57:56.799+0000] {subprocess.py:86} INFO - Output:
[2023-08-12T03:57:56.800+0000] {subprocess.py:93} INFO - bash: cannot set terminal process group (-1): Inappropriate ioctl for device
[2023-08-12T03:57:56.800+0000] {subprocess.py:93} INFO - bash: no job control in this shell
[2023-08-12T03:57:57.847+0000] {subprocess.py:93} INFO - # conda environments:
[2023-08-12T03:57:57.847+0000] {subprocess.py:93} INFO - #
[2023-08-12T03:57:57.847+0000] {subprocess.py:93} INFO - base                     /home/***/conda
[2023-08-12T03:57:57.847+0000] {subprocess.py:93} INFO - training_env          *  /home/***/conda/envs/training_env
[2023-08-12T03:57:57.847+0000] {subprocess.py:93} INFO - 
[2023-08-12T03:57:57.897+0000] {subprocess.py:93} INFO - dump training progressing
[2023-08-12T03:57:57.897+0000] {subprocess.py:93} INFO - current directory: /home/***/dog_cat_mlops
[2023-08-12T03:57:57.898+0000] {subprocess.py:93} INFO - Train successfully!
[2023-08-12T03:57:57.899+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-08-12T03:57:57.918+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=tune_dag, task_id=tune_task, execution_date=20230812T035725, start_date=20230812T035756, end_date=20230812T035757
[2023-08-12T03:57:57.956+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-12T03:57:57.964+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
